// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: appid_verification.proto

package appidpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AppIdVerificationService_VerifyAppId_FullMethodName       = "/org.cdpg.dx.auth.appid.v1.AppIdVerificationService/VerifyAppId"
	AppIdVerificationService_CheckItemAccess_FullMethodName   = "/org.cdpg.dx.auth.appid.v1.AppIdVerificationService/CheckItemAccess"
	AppIdVerificationService_ResolveDelegation_FullMethodName = "/org.cdpg.dx.auth.appid.v1.AppIdVerificationService/ResolveDelegation"
	AppIdVerificationService_GetItem_FullMethodName           = "/org.cdpg.dx.auth.appid.v1.AppIdVerificationService/GetItem"
)

// AppIdVerificationServiceClient is the client API for AppIdVerificationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ── Service ────────────────────────────────────────────────────────────────
type AppIdVerificationServiceClient interface {
	VerifyAppId(ctx context.Context, in *VerifyAppIdRequest, opts ...grpc.CallOption) (*VerifyAppIdResponse, error)
	CheckItemAccess(ctx context.Context, in *CheckItemAccessRequest, opts ...grpc.CallOption) (*CheckItemAccessResponse, error)
	ResolveDelegation(ctx context.Context, in *ResolveDelegationRequest, opts ...grpc.CallOption) (*ResolveDelegationResponse, error)
	GetItem(ctx context.Context, in *GetItemRequest, opts ...grpc.CallOption) (*GetItemResponse, error)
}

type appIdVerificationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAppIdVerificationServiceClient(cc grpc.ClientConnInterface) AppIdVerificationServiceClient {
	return &appIdVerificationServiceClient{cc}
}

func (c *appIdVerificationServiceClient) VerifyAppId(ctx context.Context, in *VerifyAppIdRequest, opts ...grpc.CallOption) (*VerifyAppIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyAppIdResponse)
	err := c.cc.Invoke(ctx, AppIdVerificationService_VerifyAppId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appIdVerificationServiceClient) CheckItemAccess(ctx context.Context, in *CheckItemAccessRequest, opts ...grpc.CallOption) (*CheckItemAccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckItemAccessResponse)
	err := c.cc.Invoke(ctx, AppIdVerificationService_CheckItemAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appIdVerificationServiceClient) ResolveDelegation(ctx context.Context, in *ResolveDelegationRequest, opts ...grpc.CallOption) (*ResolveDelegationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveDelegationResponse)
	err := c.cc.Invoke(ctx, AppIdVerificationService_ResolveDelegation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appIdVerificationServiceClient) GetItem(ctx context.Context, in *GetItemRequest, opts ...grpc.CallOption) (*GetItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetItemResponse)
	err := c.cc.Invoke(ctx, AppIdVerificationService_GetItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AppIdVerificationServiceServer is the server API for AppIdVerificationService service.
// All implementations must embed UnimplementedAppIdVerificationServiceServer
// for forward compatibility.
//
// ── Service ────────────────────────────────────────────────────────────────
type AppIdVerificationServiceServer interface {
	VerifyAppId(context.Context, *VerifyAppIdRequest) (*VerifyAppIdResponse, error)
	CheckItemAccess(context.Context, *CheckItemAccessRequest) (*CheckItemAccessResponse, error)
	ResolveDelegation(context.Context, *ResolveDelegationRequest) (*ResolveDelegationResponse, error)
	GetItem(context.Context, *GetItemRequest) (*GetItemResponse, error)
	mustEmbedUnimplementedAppIdVerificationServiceServer()
}

// UnimplementedAppIdVerificationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAppIdVerificationServiceServer struct{}

func (UnimplementedAppIdVerificationServiceServer) VerifyAppId(context.Context, *VerifyAppIdRequest) (*VerifyAppIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyAppId not implemented")
}
func (UnimplementedAppIdVerificationServiceServer) CheckItemAccess(context.Context, *CheckItemAccessRequest) (*CheckItemAccessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckItemAccess not implemented")
}
func (UnimplementedAppIdVerificationServiceServer) ResolveDelegation(context.Context, *ResolveDelegationRequest) (*ResolveDelegationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveDelegation not implemented")
}
func (UnimplementedAppIdVerificationServiceServer) GetItem(context.Context, *GetItemRequest) (*GetItemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetItem not implemented")
}
func (UnimplementedAppIdVerificationServiceServer) mustEmbedUnimplementedAppIdVerificationServiceServer() {
}
func (UnimplementedAppIdVerificationServiceServer) testEmbeddedByValue() {}

// UnsafeAppIdVerificationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AppIdVerificationServiceServer will
// result in compilation errors.
type UnsafeAppIdVerificationServiceServer interface {
	mustEmbedUnimplementedAppIdVerificationServiceServer()
}

func RegisterAppIdVerificationServiceServer(s grpc.ServiceRegistrar, srv AppIdVerificationServiceServer) {
	// If the following call panics, it indicates UnimplementedAppIdVerificationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AppIdVerificationService_ServiceDesc, srv)
}

func _AppIdVerificationService_VerifyAppId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyAppIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppIdVerificationServiceServer).VerifyAppId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppIdVerificationService_VerifyAppId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppIdVerificationServiceServer).VerifyAppId(ctx, req.(*VerifyAppIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppIdVerificationService_CheckItemAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckItemAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppIdVerificationServiceServer).CheckItemAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppIdVerificationService_CheckItemAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppIdVerificationServiceServer).CheckItemAccess(ctx, req.(*CheckItemAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppIdVerificationService_ResolveDelegation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveDelegationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppIdVerificationServiceServer).ResolveDelegation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppIdVerificationService_ResolveDelegation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppIdVerificationServiceServer).ResolveDelegation(ctx, req.(*ResolveDelegationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppIdVerificationService_GetItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppIdVerificationServiceServer).GetItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppIdVerificationService_GetItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppIdVerificationServiceServer).GetItem(ctx, req.(*GetItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AppIdVerificationService_ServiceDesc is the grpc.ServiceDesc for AppIdVerificationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AppIdVerificationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "org.cdpg.dx.auth.appid.v1.AppIdVerificationService",
	HandlerType: (*AppIdVerificationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VerifyAppId",
			Handler:    _AppIdVerificationService_VerifyAppId_Handler,
		},
		{
			MethodName: "CheckItemAccess",
			Handler:    _AppIdVerificationService_CheckItemAccess_Handler,
		},
		{
			MethodName: "ResolveDelegation",
			Handler:    _AppIdVerificationService_ResolveDelegation_Handler,
		},
		{
			MethodName: "GetItem",
			Handler:    _AppIdVerificationService_GetItem_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "appid_verification.proto",
}
